language: python
python:
    - "2.7_with_system_site_packages"
    - "3.5_with_system_site_packages"
sudo: required
install:
    - pip install tox
    - pip install coveralls 
    - pip install pytest
script: >
    tox && 
    python setup.py install && 
    py.test --cov=ngadnap tests
after_success:
    - coveralls
