language: python
python:
    - "2.7"
    - "3.4"
sudo: required
install:
    - pip install -r requirements.txt 
script: >
    tox && 
    python setup.py install && 
    py.test --cov=ngadnap tests
after_success:
    - coveralls
